# Generated by Django 4.2 on 2026-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_worker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
