# Generated by Django 6.0.2 on 2026-02-13 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='service',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='badge_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info'), ('secondary', 'Secondary'), ('dark', 'Dark')], default='secondary', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='button_link_type',
            field=models.CharField(choices=[('budget', 'Budget Page'), ('contact', 'Contact Page')], default='contact', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='button_text',
            field=models.CharField(default='View Details', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Corporate', 'Corporate'), ('Large Scale', 'Large Scale')], default='Personal', max_length=50),
        ),
    ]
