# Generated by Django 6.0.2 on 2026-02-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0004_subservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subservice',
            options={},
        ),
        migrations.RenameField(
            model_name='subservice',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='image',
        ),
        migrations.AddField(
            model_name='subservice',
            name='code',
            field=models.SlugField(default='default', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subservice',
            name='cost_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('perGuest', 'Per Guest')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='subservice',
            name='icon',
            field=models.CharField(blank=True, default='✨', max_length=10),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed'), ('perGuest', 'Per Guest')], default='fixed', max_length=20)),
                ('base_price', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='✨', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='event_services.service')),
            ],
        ),
    ]
