# Generated by Django 4.2 on 2026-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Advance Paid', 'Advance Paid'), ('Fully Paid', 'Fully Paid')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
