# Generated by Django 4.2 on 2026-04-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_worker_user'),
        ('event_services', '0007_booking_advance_amount_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. Lead Decorator, Photographer', max_length=100)),
                ('amount_due', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='event_services.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='careers.worker')),
            ],
        ),
    ]
